Repository baserproject/ucmitz, pull requests merged in 2021-07, with the labels that each got.

#177 PermissionServiceと関係する部分実装完了 #170
  plugins/baser-core/src/Model/Table/PermissionsTable.php
  plugins/baser-core/src/Service/PermissionsMockService.php
  plugins/baser-core/src/Service/PermissionsService.php
  plugins/baser-core/src/Service/PermissionsServiceInterface.php
  plugins/baser-core/src/ServiceProvider/BcServiceProvider.php
  plugins/baser-core/src/Utility/BcUtil.php
  plugins/baser-core/tests/Fixture/PermissionsFixture.php
  plugins/baser-core/tests/TestCase/Model/AppTableTest.php
  plugins/baser-core/tests/TestCase/Model/Table/PermissionsTableTest.php
  plugins/baser-core/tests/TestCase/Service/PermissionsServiceTest.php
Labels: Todo

#172 Seed追加とデータベースにおける注意点のドキュメント追加 #171
  docs/development/migration_point/database.md
  plugins/baser-core/config/Seeds/PermissionsSeed.php
  plugins/baser-core/config/Seeds/SiteConfigsSeed.php
  plugins/baser-core/src/Controller/Admin/BcAdminAppController.php
  plugins/baser-core/src/Controller/Admin/PasswordRequestsController.php
Labels: Reviewed, Todo

#167 DBログ表示
  plugins/baser-core/src/Controller/Admin/DblogsController.php
  plugins/baser-core/src/Controller/BcAppController.php
  plugins/baser-core/src/Model/Table/DblogsTable.php
  plugins/baser-core/src/Model/Table/UsersTable.php
  plugins/baser-core/src/Service/DblogsService.php
  plugins/baser-core/src/Service/DblogsServiceInterface.php
  plugins/baser-core/src/View/Helper/BcAdminHelper.php
  plugins/baser-core/tests/Fixture/DblogsFixture.php
  plugins/baser-core/tests/TestCase/Controller/Admin/DashboardControllerTest.php
  plugins/baser-core/tests/TestCase/Controller/Admin/DblogsControllerTest.php
  plugins/baser-core/tests/TestCase/Service/DblogsServiceTest.php
  plugins/baser-core/tests/TestCase/View/Helper/BcAdminHelperTest.php
  plugins/bc-admin-third/templates/Admin/Dblogs/index.php
  plugins/bc-admin-third/templates/Admin/element/Dashboard/update_log.php
  plugins/bc-admin-third/templates/Admin/element/Dblogs/index_list.php
  plugins/bc-admin-third/templates/Admin/element/Dblogs/index_row.php
  plugins/bc-admin-third/templates/Admin/element/search/dblogs_index.php
Labels: Review, Reviewed, Todo

#193 開発環境構築のドキュメントを修正
  docs/preparation/environment.md
Labels: Reviewed

#216 formhelperに関してのドキュメントを追加
  docs/development/migration_point/helper.md
Labels: Review
