Repository baserproject/ucmitz, pull requests merged in 2022-08, with the labels that each got.

#700 PluginsService::attachAllFromIds()のユニットテスト #690
  plugins/baser-core/src/Service/PluginsService.php
  plugins/baser-core/tests/TestCase/Service/PluginsServiceTest.php
Labels: Reviewed

#703 BcKeyValueBehavior::getValue() のユニットテスト #697
  plugins/baser-core/src/Model/Behavior/BcKeyValueBehavior.php
  plugins/baser-core/tests/TestCase/Model/Behavior/BcKeyValueBehaviorTest.php
Labels: Reviewed

#708 fix #693 BcValidation::fileExt() のユニットテスト #693
  plugins/baser-core/src/Model/Validation/BcValidation.php
  plugins/baser-core/tests/TestCase/Model/Table/_NotYetMigrated/BcAppTest.php
  plugins/baser-core/tests/TestCase/Model/Validation/BcValidationTest.php
Labels: Reviewed

#726 fix #711 \BaserCore\Service\PermissionsService::setDefaultAllow()のユニットテスト #711
  plugins/baser-core/src/Service/PermissionsService.php
  plugins/baser-core/tests/TestCase/Service/PermissionsServiceTest.php
Labels: Reviewed

#741 fix #715 \BaserCore\Service\SitesAdminService::getSelectableThemes() …
  plugins/baser-core/src/Service/SitesAdminService.php
  plugins/baser-core/tests/TestCase/Service/SitesAdminServiceTest.php
Labels: Reviewed

#745 fix #721 \BaserCore\TestSuite\BcTestCase tearDownFixtureManager() のユニ…
  plugins/baser-core/src/TestSuite/BcTestCase.php
  plugins/baser-core/tests/TestCase/TestSuite/BcTestCaseTest.php
Labels: Reviewed

#744 fix #723 \BaserCore\TestSuite\BcTestCase entryEventToMock() のユニットテスト
  plugins/baser-core/src/TestSuite/BcTestCase.php
  plugins/baser-core/tests/TestCase/TestSuite/BcTestCaseTest.php
Labels: Reviewed

#765 fix #756 \BaserCore\Event\BcContainerEventListener::buildContainer() …
  plugins/baser-core/src/Event/BcContainerEventListener.php
  plugins/baser-core/tests/TestCase/Event/BcContainerEventListenerTest.php
Labels: Review

#766 fix #755 \BaserCore\Event\BcContainerEventListener::implementedEvents() のユニットテスト
  plugins/baser-core/src/Event/BcContainerEventListener.php
  plugins/baser-core/tests/TestCase/Event/BcContainerEventListenerTest.php
Labels: Review

#767 fix #749 \BaserCore\Controller\Api\PluginsController::view() のユニットテスト
  plugins/baser-core/src/Controller/Api/PluginsController.php
  plugins/baser-core/tests/TestCase/Controller/Api/PluginsControllerTest.php
Labels: Review

#768 fix #750 \BaserCore\Controller\Api\SiteConfigsController::view() のユニットテスト
  plugins/baser-core/src/Controller/Api/SiteConfigsController.php
  plugins/baser-core/tests/TestCase/Controller/Api/SiteConfigsControllerTest.php
Labels: Review

#770 fix #754 \BaserCore\Controller\Api\UsersController::login() のユニットテスト
  plugins/baser-core/src/Controller/Api/UsersController.php
  plugins/baser-core/tests/TestCase/Controller/Api/UsersControllerTest.php
Labels: Review

#772 fix #752 \BaserCore\Controller\Api\UsersController::initialize() のユニットテスト
  plugins/baser-core/src/Controller/Api/UsersController.php
  plugins/baser-core/tests/TestCase/Controller/Api/UsersControllerTest.php
Labels: Review

#771 fix #753 \BaserCore\Controller\Api\UsersController::refresh_token() のユニットテスト
  plugins/baser-core/src/Controller/Api/UsersController.php
  plugins/baser-core/tests/TestCase/Controller/Api/UsersControllerTest.php
Labels: Review, Reviewed

#773 fix #764　ログ削除API
  plugins/baser-core/src/Controller/Api/DblogsController.php
  plugins/baser-core/tests/TestCase/Controller/Api/DblogsControllerTest.php
Labels: Review

#775 fix #762 ログ一覧API
  plugins/baser-core/src/Controller/Api/DblogsController.php
  plugins/baser-core/tests/TestCase/Controller/Api/DblogsControllerTest.php
Labels: Review, Reviewed

#774 fix #763 ログ新規追加API
  plugins/baser-core/src/Controller/Api/DblogsController.php
  plugins/baser-core/tests/TestCase/Controller/Api/DblogsControllerTest.php
Labels: Review, Reviewed

#785 fix #777 プラグイン有効化API実装
  plugins/baser-core/src/Controller/Api/PluginsController.php
  plugins/baser-core/src/Model/Table/PluginsTable.php
  plugins/baser-core/src/Service/PluginsService.php
  plugins/baser-core/src/Service/PluginsServiceInterface.php
  plugins/baser-core/tests/TestCase/Controller/Api/PluginsControllerTest.php
  plugins/baser-core/tests/TestCase/Model/Table/PluginsTableTest.php
Labels: Review, Reviewed

#787 fix #779 アクセス制限設定一覧取得API実装
  plugins/baser-core/src/Controller/Api/PermissionsController.php
  plugins/baser-core/tests/TestCase/Controller/Api/PermissionsControllerTest.php
Labels: Review, Reviewed

#790 fix #780 単一アクセス制限設定取得API実装
  plugins/baser-core/src/Controller/Api/PermissionsController.php
  plugins/baser-core/tests/TestCase/Controller/Api/PermissionsControllerTest.php
Labels: Review, Reviewed

#791 fix #781 アクセス制限設定編集API実装
  plugins/baser-core/src/Controller/Api/PermissionsController.php
  plugins/baser-core/tests/TestCase/Controller/Api/PermissionsControllerTest.php
Labels: Review

#793 fix #783 アクセス制限設定コピーAPI実装
  plugins/baser-core/src/Controller/Api/PermissionsController.php
  plugins/baser-core/tests/TestCase/Controller/Api/PermissionsControllerTest.php
Labels: Reviewed

#792 fix #782 アクセス制限設定削除API実装
  plugins/baser-core/src/Controller/Api/PermissionsController.php
  plugins/baser-core/tests/TestCase/Controller/Api/PermissionsControllerTest.php
Labels: Review, Reviewed

#834 fix #817 BcSearchIndexManagerBehavior::afterDelete() のユニットテスト
  plugins/baser-core/tests/TestCase/View/Helper/BcAdminHelperTest.php
  plugins/bc-search-index/src/Model/Behavior/BcSearchIndexManagerBehavior.php
  plugins/bc-search-index/tests/TestCase/Model/Behavior/BcSearchIndexManagerBehaviorTest.php
Labels: Review

#821 fix #813 BcUtil::includePluginClass() のユニットテストを調整
  plugins/baser-core/tests/TestCase/Utility/BcUtilTest.php
Labels: Review

#822 fix #810 BcAdminHelper::getTitle() のユニットテスト
  plugins/baser-core/tests/TestCase/View/Helper/BcAdminHelperTest.php
Labels: Review

#830 fix #815 BcSearchIndexManagerBehavior::setExcluded()、unsetExcluded()、isExcluded() のユニットテスト
  plugins/bc-search-index/src/Model/Behavior/BcSearchIndexManagerBehavior.php
  plugins/bc-search-index/tests/TestCase/Model/Behavior/BcSearchIndexManagerBehaviorTest.php
Labels: Review

#833 fix #816 BcSearchIndexManagerBehavior::afterSave() のユニットテスト
  plugins/baser-core/tests/TestCase/Model/Table/PagesTableTest.php
  plugins/bc-search-index/src/Model/Behavior/BcSearchIndexManagerBehavior.php
  plugins/bc-search-index/tests/TestCase/Model/Behavior/BcSearchIndexManagerBehaviorTest.php
Labels: Review

#835 fix #823 Admin\SearchIndexesController::beforeRender() のユニットテスト
  plugins/bc-search-index/src/Controller/Admin/SearchIndexesController.php
  plugins/bc-search-index/tests/TestCase/Controller/Admin/SearchIndexesControllerTest.php
Labels: Review

#836 fix #827 Api\SearchIndexesController::beforeFilter() のユニットテスト
  plugins/bc-search-index/src/Controller/Api/SearchIndexesController.php
  plugins/bc-search-index/tests/TestCase/Controller/Api/SearchIndexesControllerTest.php
Labels: Review

#811 fix #806 BcSearchBoxHelper::testDispatchShowField() のユニットテスト
  plugins/baser-core/src/View/Helper/BcSearchBoxHelper.php
  plugins/baser-core/tests/TestCase/View/Helper/BcSearchBoxHelperTest.php
Labels: Review, Reviewed

#812 fix #807 BcSearchIndex\Plugin::services() のユニットテスト
  plugins/bc-search-index/src/Plugin.php
  plugins/bc-search-index/tests/TestCase/PluginTest.php
Labels: Review, Reviewed

#819 fix #808 BcSearchIndexServiceProvider::services() のユニットテスト
  plugins/bc-search-index/src/ServiceProvider/BcSearchIndexServiceProvider.php
  plugins/bc-search-index/tests/TestCase/ServiceProvider/BcSearchIndexServiceProviderTest.php
Labels: Review, Reviewed

#686 Bc baser helper.title
  plugins/baser-core/src/View/Helper/BcBaserHelper.php
Labels: Reviewed

#831 fix #814 PagesTable::beforeSave() のユニットテスト
  plugins/baser-core/src/Model/Table/PagesTable.php
  plugins/baser-core/tests/TestCase/Model/Table/PagesTableTest.php
Labels: Review, Reviewed

#820 fix #809 SearchIndexesAdminService::getViewVarsForIndex()のユニットテスト
  plugins/baser-core/tests/Factory/SearchIndexesFactory.php
  plugins/bc-search-index/src/Service/SearchIndexesAdminService.php
  plugins/bc-search-index/tests/TestCase/Service/SearchIndexesAdminServiceTest.php
Labels: Review, Reviewed

#832 fix #818 BaserCore\Plugin::bootstrap() のユニットテストを調整
  plugins/baser-core/src/Plugin.php
  plugins/baser-core/tests/TestCase/PluginTest.php
Labels: Review, Reviewed

#841 fix #826 SearchIndexesService::changePriority() のユニットテスト
  plugins/bc-search-index/src/Service/SearchIndexesService.php
  plugins/bc-search-index/tests/TestCase/Service/SearchIndexesServiceTest.php
Labels: Review

#847 fix #828 Api\SearchIndexesController::change_priority() のユニットテスト
  plugins/bc-search-index/src/Controller/Api/SearchIndexesController.php
  plugins/bc-search-index/tests/TestCase/Controller/Api/SearchIndexesControllerTest.php
Labels: Review

#850 fix #839 Admin/SearchIndexesController::delete() のユニットテスト
  plugins/bc-search-index/src/Controller/Admin/SearchIndexesController.php
  plugins/bc-search-index/tests/TestCase/Controller/Admin/SearchIndexesControllerTest.php
Labels: Review

#848 fix#829 Api\SearchIndexesController::index() の作成
  plugins/baser-core/tests/Fixture/Factory/SearchIndexesFixture.php
  plugins/bc-search-index/src/Controller/Api/SearchIndexesController.php
  plugins/bc-search-index/tests/TestCase/Controller/Api/SearchIndexesControllerTest.php
Labels: Review, Reviewed

#860 fix #842 Admin/SearchIndexesController::reconstruct() のユニットテスト
  plugins/bc-search-index/src/Controller/Admin/SearchIndexesController.php
  plugins/bc-search-index/tests/TestCase/Controller/Admin/SearchIndexesControllerTest.php
Labels: Review, Reviewed
