Repository baserproject/ucmitz, pull requests merged in 2022-06, with the labels that each got.

#599 Login stores table test.refresh
  plugins/baser-core/src/Model/Table/LoginStoresTable.php
  plugins/baser-core/tests/TestCase/Model/Table/LoginStoresTableTest.php
Labels: Reviewed

#605 #603 固定ページ 公開期間を空にできない
  plugins/baser-core/src/Model/Table/ContentsTable.php
Labels: Review

#589 #588 固定ページ エラー表示
  plugins/baser-core/src/Controller/Component/BcAdminContentsComponent.php
  plugins/baser-core/src/Model/Table/ContentsTable.php
  plugins/baser-core/tests/TestCase/Model/Table/ContentsTableTest.php
Labels: Adjusting, Bug

#611 #600 管理画面でフォームのセキュリティがオフになっている
  plugins/baser-core/src/Controller/Admin/BcAdminAppController.php
  plugins/baser-core/src/Controller/Admin/ContentsController.php
  plugins/baser-core/src/Controller/Admin/PreviewController.php
  plugins/bc-admin-third/templates/Admin/SiteConfigs/index.php
Labels: Review

#591 #586 BcPageHelper の一部の関数を BcContentsHelper に移動
  plugins/baser-core/src/View/AppView.php
  plugins/baser-core/src/View/Helper/BcContentsHelper.php
  plugins/baser-core/src/View/Helper/BcPageHelper.php
  plugins/baser-core/tests/TestCase/View/Helper/BcContentsHelperTest.php
  plugins/baser-core/tests/TestCase/View/Helper/BcPageHelperTest.php
Labels: Todo

#644 BcAgent ユニットテスト追加
  plugins/baser-core/src/Utility/BcAgent.php
  plugins/baser-core/tests/TestCase/Utility/BcAgentTest.php
Labels: Reviewed
