Repository baserproject/ucmitz, pull requests merged in 2022-11, with the labels that each got.

#1337 fix #1311 BlogFrontService::setupPreviewForIndex のユニットテスト実装
  plugins/bc-blog/src/Service/Front/BlogFrontService.php
  plugins/bc-blog/tests/TestCase/Service/Front/BlogFrontServiceTest.php
Labels: Reviewed

#1338 SearchIndexesFrontService::getViewVarsForSearch のユニットテスト実装 fix #1329
  plugins/bc-search-index/src/Service/Front/SearchIndexesFrontService.php
  plugins/bc-search-index/tests/TestCase/Service/Front/SearchIndexesFrontServiceTest.php
  plugins/bc-search-index/tests/TestCase/Service/SearchIndexesServiceTest.php
Labels: Reviewed

#1368 fix #1364 BcContentLinkServiceProvider::services のユニットテスト実装
  plugins/bc-content-link/README.md
  plugins/bc-content-link/composer.json
  plugins/bc-content-link/src/ServiceProvider/BcContentLinkServiceProvider.php
  plugins/bc-content-link/tests/TestCase/ServiceProvider/BcContentLinkServiceProviderTest.php
Labels: Reviewed

#1366 SearchIndexesService::getIndex の見直し fix #1330
  plugins/baser-core/tests/Scenario/SearchIndexesSearchScenario.php
  plugins/bc-search-index/tests/TestCase/Service/SearchIndexesServiceTest.php
Labels: Reviewed

#1374 fix #1318 Admin/PluginsController::add() のユニットテスト実装
  plugins/baser-core/src/Controller/Admin/PluginsController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/PluginsControllerTest.php
Labels: Reviewed

#1375 fix #1325 BcFormHelper::control のユニットテスト実装
  plugins/baser-core/src/View/Helper/BcFormHelper.php
  plugins/baser-core/tests/TestCase/View/Helper/BcFormHelperTest.php
Labels: Reviewed

#1379 fix #1346 Api/ContentLinksController::delete() の APIとユニットテスト実装
  composer.json
  plugins/baser-core/src/TestSuite/BcTestCase.php
  plugins/bc-content-link/src/Controller/Api/ContentLinksController.php
  plugins/bc-content-link/src/Service/ContentLinksService.php
  plugins/bc-content-link/src/Service/ContentLinksServiceInterface.php
  plugins/bc-content-link/tests/Factory/ContentLinkFactory.php
  plugins/bc-content-link/tests/Fixture/Factory/ContentLinksFixture.php
  plugins/bc-content-link/tests/TestCase/Controller/Api/ContentLinksControllerTest.php
  plugins/bc-content-link/tests/TestCase/Service/ContentLinksServiceTest.php
Labels: Reviewed

#1380 fix #1359 ContentLinksTable::validationDefault のユニットテスト実装
  plugins/bc-content-link/src/Model/Table/ContentLinksTable.php
  plugins/bc-content-link/tests/TestCase/Model/Table/ContentLinksTableTest.php
Labels: Reviewed

#1419 addのヘッダーコメント記入
  plugins/bc-blog/src/Controller/Api/BlogCommentsController.php
Labels: Conflict

#1390 fix #1361 ContentLinksService::get のユニットテスト実装
  plugins/baser-core/src/Controller/AppController.php
  plugins/baser-core/tests/TestCase/Controller/AppControllerTest.php
  plugins/bc-content-link/src/Controller/Api/ContentLinksController.php
  plugins/bc-content-link/src/Service/ContentLinksService.php
  plugins/bc-content-link/tests/TestCase/Controller/Api/ContentLinksControllerTest.php
  plugins/bc-content-link/tests/TestCase/Service/ContentLinksServiceTest.php
Labels: Reviewed

#1431 fix #1397 Admin/BlogCommentsController::delete のユニットテスト実装
  plugins/bc-blog/src/Controller/Admin/BlogCommentsController.php
  plugins/bc-blog/tests/Factory/BlogCommentFactory.php
  plugins/bc-blog/tests/Scenario/BlogCommentsScenario.php
  plugins/bc-blog/tests/TestCase/Controller/Admin/BlogCommentsControllerTest.php
Labels: Reviewed

#1444 BcUploadBehavior::renameToBasenameFieldsにヘッダー記入
  plugins/baser-core/src/Model/Behavior/BcUploadBehavior.php
  plugins/bc-blog/src/Service/BlogCommentsService.php
Labels: Reviewed

#1437 fix #1404 Admin/BlogCommentsController::unpublish のユニットテスト実装
  plugins/bc-blog/src/Controller/Admin/BlogCommentsController.php
  plugins/bc-blog/tests/Scenario/BlogCommentsScenario.php
  plugins/bc-blog/tests/TestCase/Controller/Admin/BlogCommentsControllerTest.php
Labels: Reviewed

#1445 fix #1408 Admin/BlogPostsController::add のユニットテスト実装
  plugins/bc-blog/src/Controller/Admin/BlogPostsController.php
  plugins/bc-blog/tests/TestCase/Controller/Admin/BlogPostsControllerTest.php
Labels: Reviewed

#1433 fix #1357 ContentLinksController::view のユニットテスト実装
  plugins/bc-content-link/src/Controller/ContentLinksController.php
  plugins/bc-content-link/tests/TestCase/Controller/ContentLinksControllerTest.php
Labels: Reviewed

#1434 fix #1354 Admin/ContentLinksController::edit のユニットテスト実装
  plugins/bc-content-link/src/Controller/Admin/ContentLinksController.php
  plugins/bc-content-link/tests/TestCase/Controller/Admin/ContentLinksControllerTest.php
Labels: Reviewed

#1420 fix #1313 BcRedirectSubSiteFilter::process のユニットテスト実装
  plugins/baser-core/src/Middleware/BcRedirectSubSiteFilter.php
  plugins/baser-core/tests/TestCase/Middleware/BcRedirectSubSiteFilterTest.php
Labels: Reviewed

#1461 fix #1422 Admin/BlogTagsController::delete のユニットテスト実装
  plugins/bc-blog/src/Controller/Admin/BlogTagsController.php
  plugins/bc-blog/tests/Factory/BlogTagFactory.php
  plugins/bc-blog/tests/TestCase/Controller/Admin/BlogTagsControllerTest.php
Labels: Reviewed

#1428 fix #1362 ContentLinksService::create のユニットテスト実装
  plugins/bc-content-link/src/Service/ContentLinksService.php
  plugins/bc-content-link/tests/TestCase/Service/ContentLinksServiceTest.php
Labels: Reviewed

#1464 fix #1457 BlogCommentsService::get のユニットテスト実装
  plugins/bc-blog/src/Service/BlogCommentsService.php
  plugins/bc-blog/tests/TestCase/Service/BlogCommentsServiceTest.php
Labels: Reviewed

#1466 fix #1460 BlogCommentsService::unpublish のユニットテスト実装
  plugins/bc-blog/src/Service/BlogCommentsService.php
  plugins/bc-blog/tests/TestCase/Service/BlogCommentsServiceTest.php
Labels: Reviewed

#1468 fix #1455 BlogCommentsService::batch のユニットテスト実装
  plugins/bc-blog/src/Service/BlogCommentsService.php
  plugins/bc-blog/tests/TestCase/Service/BlogCommentsServiceTest.php
Labels: Reviewed

#1475 fix #1413 Admin/BlogPostsController::index のユニットテスト実装
  plugins/bc-blog/src/Controller/Admin/BlogPostsController.php
  plugins/bc-blog/tests/TestCase/Controller/Admin/BlogPostsControllerTest.php
Labels: Reviewed

#1488 fix #1447 BlogCategoriesTable::hasNewCategoryAddablePermission のユニットテスト実装
  plugins/bc-blog/src/Model/Table/BlogCategoriesTable.php
  plugins/bc-blog/tests/TestCase/Model/BlogCategoriesTableTest.php
Labels: Reviewed

#1489 fix #1426 Api/BlogCommentsController::batch のユニットテスト実装
  plugins/bc-blog/src/Controller/Api/BlogCommentsController.php
  plugins/bc-blog/tests/TestCase/Controller/Api/BlogCommentsControllerTest.php
  plugins/bc-blog/tests/TestCase/Controller/Api/BlogContentsControllerTest.php
Labels: Reviewed

#1490 fix #1449 BcUploadBehavior::renameToBasenameFields のユニットテスト実装
  plugins/baser-core/src/Model/Behavior/BcUploadBehavior.php
  plugins/baser-core/tests/TestCase/Model/Behavior/BcUploadBehaviorTest.php
Labels: Reviewed

#1511 fix #1501 BlogFrontService::getViewVarsForSingle のユニットテスト実装
  plugins/bc-blog/src/Service/Front/BlogFrontService.php
  plugins/bc-blog/tests/Factory/BlogContentFactory.php
  plugins/bc-blog/tests/TestCase/Service/Front/BlogFrontServiceTest.php
Labels: Reviewed, Conflict

#1524 fix #1500 BlogFrontService::getViewVarsForArchivesByTag のユニットテスト実装
  plugins/bc-blog/src/Service/Front/BlogFrontService.php
  plugins/bc-blog/tests/TestCase/Service/Front/BlogFrontServiceTest.php
Labels: Conflict

#1520 fix 1507 Admin/MailContentsController::initialize のユニットテスト実装
  plugins/bc-mail/src/Controller/Admin/MailContentsController.php
  plugins/bc-mail/tests/TestCase/Controller/Admin/MailContentsControllerTest.php
Labels: Reviewed

#1474 fix #1415 Admin/BlogPostsController::publish のユニットテスト実装
  plugins/bc-blog/src/Controller/Admin/BlogPostsController.php
  plugins/bc-blog/tests/Factory/BlogPostFactory.php
  plugins/bc-blog/tests/TestCase/Controller/Admin/BlogPostsControllerTest.php
  plugins/bc-blog/tests/TestCase/Service/Front/BlogFrontServiceTest.php
Labels: Reviewed

#1551 fix #1499 BlogFrontService::getViewVarsForArchivesByDate のユニットテスト実装
  plugins/bc-blog/src/Service/Front/BlogFrontService.php
  plugins/bc-blog/tests/TestCase/Service/Front/BlogFrontServiceTest.php
Labels: Reviewed
