Repository baserproject/ucmitz, pull requests merged in 2022-09, with the labels that each got.

#845 fix #825 SearchIndexesService::getIndex() のユニットテスト
  plugins/bc-search-index/src/Service/SearchIndexesService.php
  plugins/bc-search-index/tests/TestCase/Service/SearchIndexesServiceTest.php
Labels: Review, Reviewed

#849 fix #837 BcTestCase::setFixtureTruncate()、getFixtureStrategy() のユニットテスト
  plugins/baser-core/src/TestSuite/BcTestCase.php
  plugins/baser-core/tests/TestCase/TestSuite/BcTestCaseTest.php
Labels: Review, Reviewed

#863 fix #846 Api/SearchIndexesController::batch() のユニットテスト
  plugins/bc-search-index/src/Controller/Api/SearchIndexesController.php
  plugins/bc-search-index/tests/TestCase/Controller/Api/SearchIndexesControllerTest.php
Labels: Review

#865 fix #852 PluginsService::batch() のユニットテスト
  plugins/baser-core/src/Service/PluginsService.php
  plugins/baser-core/tests/TestCase/Service/PluginsServiceTest.php
Labels: Review

#859 fix #840 SearchIndexesService::delete() のユニットテスト
  plugins/bc-search-index/src/Service/SearchIndexesService.php
  plugins/bc-search-index/tests/TestCase/Service/SearchIndexesServiceTest.php
Labels: Review, Reviewed

#861 fix #843 Api/SearchIndexesController::delete() の作成
  plugins/bc-search-index/src/Controller/Api/SearchIndexesController.php
  plugins/bc-search-index/tests/TestCase/Controller/Api/SearchIndexesControllerTest.php
Labels: Review, Reviewed

#862 fix #844 Api/SearchIndexesController::reconstruct()
  plugins/bc-search-index/src/Controller/Api/SearchIndexesController.php
  plugins/bc-search-index/tests/TestCase/Controller/Api/SearchIndexesControllerTest.php
Labels: Review, Reviewed

#866 fix #853 PluginsService::getNamesById() のユニットテスト
  plugins/baser-core/src/Service/PluginsService.php
  plugins/baser-core/tests/TestCase/Service/PluginsServiceTest.php
Labels: Review, Reviewed

#867 fix #854 PermissionsService::batch() のユニットテスト
  plugins/baser-core/src/Service/PermissionsService.php
  plugins/baser-core/tests/Factory/PermissionFactory.php
  plugins/baser-core/tests/TestCase/Service/PermissionsServiceTest.php
Labels: Review

#868 fix #855 test PermissionsService::getNamesById() のユニットテスト
  plugins/baser-core/src/Service/PermissionsService.php
  plugins/baser-core/tests/TestCase/Service/PermissionsServiceTest.php
Labels: Review

#864 fix #851 SearchIndexesService::batch() のユニットテスト
  plugins/bc-search-index/src/Service/SearchIndexesService.php
  plugins/bc-search-index/tests/TestCase/Service/SearchIndexesServiceTest.php
Labels: Review, Reviewed

#869 fix #856 ContentsService::batch() のユニットテスト #856
  plugins/baser-core/src/Service/ContentsService.php
  plugins/baser-core/tests/TestCase/Service/ContentsServiceTest.php
Labels: Review

#876 fix #870 ThemesAdminService::getViewVarsForIndex() のユニットテスト（dev-#8）
  plugins/baser-core/src/Service/ThemesAdminService.php
  plugins/baser-core/tests/TestCase/Service/ThemesAdminServiceTest.php
Labels: Review

#878 fix #857 ContentsService::getTitlesById() のユニットテスト
  plugins/baser-core/src/Service/ContentsService.php
  plugins/baser-core/tests/TestCase/Service/ContentsServiceTest.php
Labels: Review

#877 fix #871 Admin\ThemesController::index() のユニットテスト（dev-#8）
  plugins/baser-core/src/Controller/Admin/ThemesController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/ThemesControllerTest.php
Labels: Review, Reviewed

#892 fix #889 ThemesService::delete() のユニットテスト（dev-#8）
  plugins/baser-core/src/Service/ThemesService.php
  plugins/baser-core/tests/TestCase/Service/ThemesServiceTest.php
Labels: Review

#896 fix #885 ThemeService::getThemesDefaultDataInfo のユニットテスト（dev-#8)
  plugins/baser-core/src/Service/ThemesService.php
  plugins/baser-core/tests/TestCase/Service/ThemesServiceTest.php
Labels: Review, Reviewed

#894 fix #887 ThemesService::copy() のユニットテスト #887
  plugins/baser-core/src/Service/ThemesService.php
  plugins/baser-core/tests/TestCase/Service/ThemesServiceTest.php
Labels: Review, Reviewed

#895 fix #872 Admin\ThemesController::screenshot() のユニットテスト（dev-#8）
  plugins/baser-core/src/Controller/Admin/ThemesController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/ThemesControllerTest.php
Labels: Review, Reviewed

#909 fix #874 Admin\ThemesController::get_market_themes() のユニットテスト（dev-#8）
  plugins/baser-core/src/Controller/Admin/ThemesController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/ThemesControllerTest.php
Labels: Review

#911 fix #875 ThemesService::getMarketThemes() のユニットテスト（dev-#8）
  plugins/baser-core/src/Service/ThemesService.php
  plugins/baser-core/tests/TestCase/Service/ThemesServiceTest.php
Labels: Review

#912 fix #879 BcUtil::testGetThemesPlugins() のユニットテスト（dev-#8）
  plugins/baser-core/src/Utility/BcUtil.php
  plugins/baser-core/tests/TestCase/Utility/BcUtilTest.php
Labels: Review

#910 fix #873 ThemesService::getIndex() のユニットテスト（dev-#8）
  plugins/baser-core/src/Service/ThemesService.php
  plugins/baser-core/tests/TestCase/Service/ThemesServiceTest.php
Labels: Review, Reviewed

#917 fix #881 BcPlugin::applyAsTheme() のユニットテスト（dev-#8）
  plugins/baser-core/src/BcPlugin.php
  plugins/baser-core/tests/TestCase/BcPluginTest.php
Labels: Reviewed

#913 fix #880 BcUtil::getCurrentThemesPlugins() のユニットテスト（dev-#8）
  plugins/baser-core/src/Utility/BcUtil.php
  plugins/baser-core/tests/TestCase/Utility/BcUtilTest.php
Labels: Review, Reviewed

#947 fix #883 ThemeService::apply() のユニットテスト（dev-#8）
  plugins/baser-core/src/Service/ThemesService.php
  plugins/baser-core/tests/TestCase/Service/ThemesServiceTest.php
Labels: Review, Reviewed

#948 fix #884 ThemeService::getThemesPluginsInfo() のユニットテスト（dev-#8）
  plugins/baser-core/tests/TestCase/Service/ThemesServiceTest.php
Labels: Reviewed

#962 fix #885 ThemeService::getThemesDefaultDataInfo のユニットテスト（dev-#8）
  plugins/baser-core/src/Service/ThemesService.php
  plugins/baser-core/tests/TestCase/Service/ThemesServiceTest.php
Labels: Review

#963 fix #886 Admin/ThemesController::copy() のユニットテスト（dev-#8)
  plugins/baser-core/src/Controller/Admin/ThemesController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/ThemesControllerTest.php
Labels: Review

#964 fix #888 Admin/ThemesController::delete() のユニットテスト（dev-#8）
  plugins/baser-core/src/Controller/Admin/ThemesController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/ThemesControllerTest.php
Labels: Review

#946 fix #929 テーマ一覧を取得するAPIを実装（dev-#8）
  plugins/baser-core/src/Controller/Api/ThemesController.php
  plugins/baser-core/tests/TestCase/Controller/Api/ThemesControllerTest.php
Labels: Review, Reviewed

#967 fix #891 ThemesService::createDownloadToTmp() のユニットテスト（dev-#8）
  plugins/baser-core/src/Service/ThemesService.php
  plugins/baser-core/tests/TestCase/Service/ThemesServiceTest.php
Labels: Review, Reviewed

#971 fix #961 UtilitiesService::deleteLog() のユニットテスト #961
  plugins/baser-core/src/Service/UtilitiesService.php
  plugins/baser-core/tests/TestCase/Service/UtilitiesServiceTest.php
Labels: Reviewed

#965 fix #931 新しいテーマをアップロードするAPIを実装（dev-#8） #931
  plugins/baser-core/src/Controller/Api/PermissionsController.php
  plugins/baser-core/src/Controller/Api/ThemesController.php
  plugins/baser-core/tests/TestCase/Controller/Api/ThemesControllerTest.php
Labels: Reviewed

#966 fix #932 テーマを適用するAPIを実装（dev-#8）
  plugins/baser-core/src/Controller/Api/ThemesController.php
  plugins/baser-core/tests/TestCase/Controller/Api/ThemesControllerTest.php
Labels: Review, Reviewed

#973 fix #905 ThemesController::download_default_data_pattern() のユニットテスト（dev-#8)
  plugins/baser-core/src/Controller/Admin/ThemesController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/ThemesControllerTest.php
Labels: Review, Reviewed

#968 fix #933 テーマの初期データを読み込むAPIを実装（dev-#8） #933
  plugins/baser-core/src/Controller/Api/ThemesController.php
Labels: Reviewed

#987 fix #918 BcDatabaseService::loadCsvToArray() のユニットテスト（dev-#8） #918
  plugins/baser-core/src/Service/BcDatabaseService.php
  plugins/baser-core/tests/TestCase/Service/BcDatabaseServiceTest.php
Labels: Review

#986 fix #916 BcDatabaseService::resetAllTables() のユニットテスト（dev-#8）
  plugins/baser-core/src/Service/BcDatabaseService.php
  plugins/baser-core/tests/TestCase/Service/BcDatabaseServiceTest.php
Labels: Reviewed

#1000 fix #900 BcDatabaseService::_dbEncToPhp() のユニットテスト（dev-#8）
  plugins/baser-core/src/Service/BcDatabaseService.php
  plugins/baser-core/tests/TestCase/Service/BcDatabaseServiceTest.php
Labels: Conflict

#996 fix #993 Api/ThemesController::get_market_themes() の実装 #993
  plugins/baser-core/src/Controller/Api/ThemesController.php
  plugins/baser-core/tests/TestCase/Controller/Api/ThemesControllerTest.php
Labels: Reviewed

#994 fix #897 BcDatabaseService::writeCsv() のユニットテスト（dev-#8）
  plugins/baser-core/src/Service/BcDatabaseService.php
  plugins/baser-core/tests/TestCase/Service/BcDatabaseServiceTest.php
Labels: Reviewed

#1012 fix #1004　ユーティリティ：ツリー構造チェックAPIを実装
  plugins/baser-core/src/Controller/Api/UtilitiesController.php
  plugins/baser-core/tests/TestCase/Controller/Api/UtilitiesControllerTest.php
Labels: Reviewed

#1019 fix #1007 ユーティリティ：バックアップよりレストアAPIを実装
  plugins/baser-core/src/Controller/Api/UtilitiesController.php
  plugins/baser-core/src/Service/BcDatabaseService.php
  plugins/baser-core/tests/TestCase/Controller/Api/UtilitiesControllerTest.php
Labels: Reviewed

#1022 Dev #941 UtilitiesController::verity_contents_tree() のユニットテスト
  plugins/baser-core/src/Controller/Admin/UtilitiesController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/UtilitiesControllerTest.php
Labels: Reviewed

#1027 fix #1009 ユーティリティ：ログファイルを削除APIを実装
  plugins/baser-core/src/Controller/Api/UtilitiesController.php
  plugins/baser-core/tests/TestCase/Controller/Api/UtilitiesControllerTest.php
Labels: Review

#1034 fix #959 UtilitiesController::log_maintenance () のユニットテスト
  plugins/baser-core/src/Controller/Admin/UtilitiesController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/UtilitiesControllerTest.php
Labels: Reviewed

#1030 fix #955 UtilitiesController::initialize() のユニットテスト
  plugins/baser-core/src/Controller/Admin/UtilitiesController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/UtilitiesControllerTest.php
Labels: Reviewed

#1031 fix #956 UtilitiesController::credit() のユニットテスト
  plugins/baser-core/src/Controller/Admin/UtilitiesController.php
  plugins/baser-core/tests/TestCase/Controller/Admin/UtilitiesControllerTest.php
Labels: Reviewed

#1040 fix #953 BcAdminFormHelper::postLink() のユニットテスト
  plugins/baser-core/src/View/Helper/BcAdminFormHelper.php
  plugins/baser-core/tests/TestCase/View/Helper/BcAdminFormHelperTest.php
Labels: Reviewed

#1039 fix #960 UtilitiesService::createLogZip() のユニットテスト
  plugins/baser-core/src/Service/UtilitiesService.php
  plugins/baser-core/tests/TestCase/Service/UtilitiesServiceTest.php
Labels: Reviewed
