Repository baserproject/ucmitz, pull requests merged in 2023-02, with the labels that each got.

#1791 fix BcDatabaseService::getDataSource のユニットテスト実装 #1689
  plugins/baser-core/src/Service/BcDatabaseService.php
  plugins/baser-core/tests/TestCase/Service/BcDatabaseServiceTest.php
Labels: Reviewed

#1782 fix #1770 テーマファイルAPI ファイル編集
  plugins/bc-theme-file/src/Controller/Admin/ThemeFilesController.php
  plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
  plugins/bc-theme-file/src/Service/ThemeFilesService.php
  plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFilesControllerTest.php
Labels: Reviewed

#1783 fix #1772 テーマファイルAPI ファイル削除
  plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
  plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFilesControllerTest.php
Labels: Reviewed

#1784 fix #1773 テーマファイルAPI ファイルコピー
  plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
  plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFilesControllerTest.php
Labels: Reviewed

#1786 fix #1775 テーマファイルAPI ファイルを表示
  plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
  plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFilesControllerTest.php
Labels: Reviewed

#1815 fix #1802 テーマフォルダAPI フォルダ編集
  plugins/bc-theme-file/src/Controller/Api/ThemeFoldersController.php
  plugins/bc-theme-file/src/Service/BcThemeFileService.php
  plugins/bc-theme-file/src/Service/BcThemeFileServiceInterface.php
  plugins/bc-theme-file/src/Service/ThemeFilesService.php
  plugins/bc-theme-file/src/Service/ThemeFoldersService.php
  plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFoldersControllerTest.php
  plugins/bc-theme-file/tests/TestCase/Service/BcThemeFileServiceTest.php
Labels: Reviewed

#1787 fix #1776 テーマファイルAPI 画像を表示
  plugins/bc-theme-file/src/Controller/Admin/ThemeFilesController.php
  plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
  plugins/bc-theme-file/src/Service/Admin/ThemeFilesAdminService.php
  plugins/bc-theme-file/src/Service/ThemeFilesService.php
  plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFilesControllerTest.php
  plugins/bc-theme-file/tests/TestCase/Service/ThemeFilesServiceTest.php
Labels: Reviewed

#1816 fix #1803 テーマフォルダAPI フォルダ削除
  plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
  plugins/bc-theme-file/src/Controller/Api/ThemeFoldersController.php
  plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFoldersControllerTest.php
Labels: Reviewed

#1819 fix #1807 テーマフォルダAPI フォルダを表示
  plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
  plugins/bc-theme-file/src/Controller/Api/ThemeFoldersController.php
  plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFoldersControllerTest.php
Labels: Reviewed

#1818 fix #1805 テーマフォルダAPI ファイルアップロード
  plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
  plugins/bc-theme-file/src/Controller/Api/ThemeFoldersController.php
  plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFilesControllerTest.php
  plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFoldersControllerTest.php
Labels: Reviewed

#1799 fix #1777 テーマファイルAPI 画像のサムネイルを表示
  plugins/bc-theme-file/src/Controller/Admin/ThemeFilesController.php
  plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
  plugins/bc-theme-file/src/Service/Admin/ThemeFilesAdminService.php
  plugins/bc-theme-file/src/Service/ThemeFilesService.php
  plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFilesControllerTest.php
  plugins/bc-theme-file/tests/TestCase/Service/ThemeFilesServiceTest.php
Labels: Reviewed, Conflict

#1865 ブログカテゴリ追加処理を修正
  plugins/bc-admin-third/src/bc_blog/js/admin/blog_posts/form.js
  plugins/bc-admin-third/webroot/bc_blog/js/admin/blog_posts/form.bundle.js
  plugins/bc-admin-third/webroot/bc_blog/js/admin/blog_posts/form.bundle.js.map
Labels: Bug

#1838 fix #1824 メールフィールド API　編集
  plugins/bc-mail/src/Controller/Api/MailFieldsController.php
  plugins/bc-mail/tests/Scenario/MailFieldsScenario.php
  plugins/bc-mail/tests/TestCase/Controller/Api/MailFieldsControllerTest.php
Labels: Conflict

#1843 fix #1831 メールコンテンツAPI 編集
  plugins/bc-mail/src/Controller/Api/MailContentsController.php
  plugins/bc-mail/tests/TestCase/Controller/Api/MailContentsControllerTest.php
Labels: Conflict

#1844 fix #1832 メールコンテンツAPI 削除
  plugins/bc-mail/src/Controller/Api/MailContentsController.php
  plugins/bc-mail/tests/TestCase/Controller/Api/MailContentsControllerTest.php
Labels: Reviewed

#1861 fix #1849 アップロードファイルAPI　新規追加
  plugins/bc-uploader/src/Controller/Api/UploaderFilesController.php
  plugins/bc-uploader/tests/TestCase/Controller/UploaderFilesControllerTest.php
Labels: Conflict

#1862 fix #1850 アップロードファイルAPI 編集
  plugins/bc-uploader/src/Controller/Api/UploaderFilesController.php
  plugins/bc-uploader/tests/TestCase/Controller/UploaderFilesControllerTest.php
Labels: Conflict
